# Generated by Django 4.2.7 on 2023-11-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qr_code_image',
            field=models.ImageField(default=1, upload_to='qr_code'),
            preserve_default=False,
        ),
    ]
