# Generated by Django 4.2.7 on 2023-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='qr_code_image',
            field=models.ImageField(null=True, upload_to='qr_code'),
        ),
    ]
